# Generated by Django 3.1.7 on 2021-02-21 16:32

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('sweetness', models.CharField(choices=[('Dry', 'Dry'), ('Semi-dry', 'Semi-dry'), ('Semi-sweet', 'Semi-sweet'), ('Sweet', 'Sweet')], max_length=255)),
                ('grape_variety', models.CharField(max_length=255)),
                ('production_year', models.IntegerField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('url', models.URLField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('grade', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10, message='Grades are on a scale of 0-10'), django.core.validators.MinValueValidator(0, message='Grades are on a scale of 0-10')])),
                ('favourite', models.BooleanField(default=None, null=True)),
            ],
        ),
    ]
